### ISSUE TITLE
Missed case for listing cStor volumes

### ISSUE THREAD

**Issue by vaniisgh** [openebs/openebsctl#1]
When a PVC is provisioned and the CStorVolume might not be created the current logic is not sufficient to list the instances.

**Comment by kmova** [comment]
This can be expanded into a few more test cases like:
- Checking what is the minimum OpenEBS version required for openebsctl to work. And in case user tries with older openebs version, does it gracefully error out?
- Test the commands by breaking the components - for example if listing cstor volume:
   - create a PV (with reclaim policy as retain), delete the PVC
   - create a PV - delete manually some of the sub CRs and check if openebsctl can gracefully validate and display missing information

**Comment by Abhinandan-Purkait** [comment]
We have tried the above mentioned cases and these are the observations:
- If `CstorVolume` is not created, the get command will not the list the volume.
- If PVC is deleted and the volume has a reclaim policy of `Retain`, then the flow works as expected, the `CstorVolume` is listed and the describe also works without any error.
- If subCR like `CVC` is deleted then the`CstorVolume` and the `CVR` also gets deleted and thus it is will not list the `CstorVolume`. Although if we do a `kubectl get pv` we will be able to see the PV and if we pass the PV name in the `kubectl openebs volume describe` command it will show a error i.e. `failed to execute volume info command, getting cStor volumes: error while while getting volume <volume name>: cstorvolumes.cstor.openebs.io "<volume name>" not found`.
- If subCR like `CVR` is deleted then the flow works as expected i.e the `CstorVolume` will be listed and on describe in the replica section it shows `None of the replicas are running`
