### ISSUE TITLE
Investigation: Not all tools of GolangCI lint are running in the CI

### ISSUE THREAD

**Issue by vharsh** [openebs/openebsctl#105]
There is likely some mis-configuration in the CI which is ignoring minor linters like gosimpl, golint, etc from raising red flags. E.g.

```go
func awesome() {
    ....
    if something {
        return nil, err
    } else {
        return value, nil
    }
} // end of function
```
should raise warnings to the very least, but it isn't being raised currently.

# Starting points for completion

1. Take the [Go-Tour](https://tour.golang.org) if you aren't up to speed with Golang
2. Read some basics about Continuous Integration and something about [GolangCI Lint](https://golangci-lint.run) and what [linters](https://golangci-lint.run/usage/linters) it supports.
3. Enable some of the linters like `revive`, `gofmt`, `errorlint`, etc.
4. Fix the linting issues

**Comment by Amishakumari544** [comment]
Taking this .

**Comment by vharsh** [comment]
@Amishakumari544 Thanks for taking this up, here's the config file for GolangCI Linter -> https://github.com/openebs/openebsctl/blob/develop/.golangci.yml . If you face any problems do ask around in #openebs-dev

**Comment by Abhishek-kumar09** [comment]
Does https://github.com/openebs/openebsctl/pull/109 solves the issue completely?

**Comment by vharsh** [comment]
> Does #109 solves the issue completely?

Looks like some caching issue is present, it might not be running on all the codebase. The official example does suggest skipping some caches, need to try this once.

https://github.com/golangci/golangci-lint/blob/master/.github/workflows/pr.yml#L36

**Comment by Amishakumari544** [comment]
no I checked for windows its not working properly @Abhishek-kumar09

**Comment by vharsh** [comment]
> no I checked for windows its not working properly @Abhishek-kumar09

As of now I'm totally clueless why it didn't work for windows, @Amishakumari544 can you run `echo %errorlevel%` just after running `golangci-lint run` and share the output. I'm suspecting something could be wrong on your setup or you've not installed Golang correctly. 

Also share output of
```bash
go version
echo %errorlevel%
```

Credits: https://stackoverflow.com/questions/334879/how-do-i-get-the-application-exit-code-from-a-windows-command-line

**Comment by vharsh** [comment]
Interesting finding, it didn't work correctly even after I cleared my golangci-lint cache
```bash
➜  openebsctl git:(fixes) ✗ cd ~/.cache/golangci-lint/
➜  golangci-lint l
00/  0b/  16/  21/  2c/  37/  42/  4d/  58/  63/  6e/  79/  84/  8f/  9a/  a5/  b0/  bb/  c6/  d1/  dc/  e7/  f2/  fd/
01/  0c/  17/  22/  2d/  38/  43/  4e/  59/  64/  6f/  7a/  85/  90/  9b/  a6/  b1/  bc/  c7/  d2/  dd/  e8/  f3/  fe/
02/  0d/  18/  23/  2e/  39/  44/  4f/  5a/  65/  70/  7b/  86/  91/  9c/  a7/  b2/  bd/  c8/  d3/  de/  e9/  f4/  ff/
03/  0e/  19/  24/  2f/  3a/  45/  50/  5b/  66/  71/  7c/  87/  92/  9d/  a8/  b3/  be/  c9/  d4/  df/  ea/  f5/  README
04/  0f/  1a/  25/  30/  3b/  46/  51/  5c/  67/  72/  7d/  88/  93/  9e/  a9/  b4/  bf/  ca/  d5/  e0/  eb/  f6/  trim.txt
05/  10/  1b/  26/  31/  3c/  47/  52/  5d/  68/  73/  7e/  89/  94/  9f/  aa/  b5/  c0/  cb/  d6/  e1/  ec/  f7/
06/  11/  1c/  27/  32/  3d/  48/  53/  5e/  69/  74/  7f/  8a/  95/  a0/  ab/  b6/  c1/  cc/  d7/  e2/  ed/  f8/
07/  12/  1d/  28/  33/  3e/  49/  54/  5f/  6a/  75/  80/  8b/  96/  a1/  ac/  b7/  c2/  cd/  d8/  e3/  ee/  f9/
08/  13/  1e/  29/  34/  3f/  4a/  55/  60/  6b/  76/  81/  8c/  97/  a2/  ad/  b8/  c3/  ce/  d9/  e4/  ef/  fa/
09/  14/  1f/  2a/  35/  40/  4b/  56/  61/  6c/  77/  82/  8d/  98/  a3/  ae/  b9/  c4/  cf/  da/  e5/  f0/  fb/
0a/  15/  20/  2b/  36/  41/  4c/  57/  62/  6d/  78/  83/  8e/  99/  a4/  af/  ba/  c5/  d0/  db/  e6/  f1/  fc/
➜  golangci-lint rm -rf *
zsh: sure you want to delete more than 100 files in /home/harsh/.cache/golangci-lint [yn]? %                                       ➜  golangci-lint ls
00  09  12  1b  24  2d  36  3f  48  51  5a  63  6c  75  7e  87  90  99  a2  ab  b4  bd  c6  cf  d8  e1  ea  f3  fc
01  0a  13  1c  25  2e  37  40  49  52  5b  64  6d  76  7f  88  91  9a  a3  ac  b5  be  c7  d0  d9  e2  eb  f4  fd
02  0b  14  1d  26  2f  38  41  4a  53  5c  65  6e  77  80  89  92  9b  a4  ad  b6  bf  c8  d1  da  e3  ec  f5  fe
03  0c  15  1e  27  30  39  42  4b  54  5d  66  6f  78  81  8a  93  9c  a5  ae  b7  c0  c9  d2  db  e4  ed  f6  ff
04  0d  16  1f  28  31  3a  43  4c  55  5e  67  70  79  82  8b  94  9d  a6  af  b8  c1  ca  d3  dc  e5  ee  f7  README
05  0e  17  20  29  32  3b  44  4d  56  5f  68  71  7a  83  8c  95  9e  a7  b0  b9  c2  cb  d4  dd  e6  ef  f8  trim.txt
06  0f  18  21  2a  33  3c  45  4e  57  60  69  72  7b  84  8d  96  9f  a8  b1  ba  c3  cc  d5  de  e7  f0  f9
07  10  19  22  2b  34  3d  46  4f  58  61  6a  73  7c  85  8e  97  a0  a9  b2  bb  c4  cd  d6  df  e8  f1  fa
08  11  1a  23  2c  35  3e  47  50  59  62  6b  74  7d  86  8f  98  a1  aa  b3  bc  c5  ce  d7  e0  e9  f2  fb
➜  golangci-lint rm -rf *
zsh: sure you want to delete more than 100 files in /home/harsh/.cache/golangci-lint [yn]? y
➜  golangci-lint ls
➜  golangci-lint cd -
~/code/go/src/github.com/openebs/openebsctl
➜  openebsctl git:(fixes) ✗ golangci-lint run
➜  openebsctl git:(fixes) ✗ git status
```

**Comment by nevosial** [comment]
Hello I would like to work on this .
Can you help me where to get started as I am a new contributor.

**Comment by vharsh** [comment]
@nevosial Sure, this will require some GoLang familiarity. You can clone the code, read a bit about some go linting tools(even try running them) from the official docs and then read about GolangCI Lint(which basically runs all the official go tools and a bunch of other 3rd party ones.

As an exercise, consider breaking some rule, e.g. breaking golint's rule about documenting an exported function, you'd get an error from the `golint` CLI but not from the golangci-lint binary which is supposed to be running the same tool `golint` as it is in the configuration, we need to figure out why some of the tools aren't being run. This issue has been seen in the GitHub actions and in local system as well. [Example#1](https://github.com/openebs/openebsctl/pull/115#discussion_r729454687)

**Comment by pawanpraka1** [comment]
@vharsh should we close this issue or there is anything pending for this?

**Comment by vharsh** [comment]
@pawanpraka1 This issue hasn't been resolved yet, I'll move it to TODO and I'll create an issue in golangci-lint repo and ask for help.

**Comment by vharsh** [comment]
This has now been fixed, there was a small error in the configuration of the linter, I have fixed it and some also fixed some preliminary issues and added https://github.com/openebs/openebsctl/issues/146 for new contributors from the community.
