### ISSUE TITLE
Gitpodify openebs/openebsctl for easier contribution

### ISSUE THREAD

**Issue by princerachit** [openebs/openebsctl#125]
Setting up environment like installing various dependencies, having right version of tools might discourage potential contributors. Having this repo gitpodified would set up dev env with one click.

One of the repository is already gitpodified.

https://github.com/openebs/cstor-operators/blob/develop/.gitpod.yml

**Comment by princerachit** [comment]
I am working on this @vharsh @shovanmaity . Is this eligible for hacktoberfest?

**Comment by vharsh** [comment]
Thank you for your awesome contributions @princerachit
