### ISSUE TITLE
Add feature to view the jiva volume upgrade status

### ISSUE THREAD

**Issue by vharsh** [openebs/openebsctl#128]
As per https://github.com/openebs/openebsctl/pull/115 the feature has been implemented to schedule the upgrade job to upgrade the Jiva volume data plane components to match the version of the jiva control plane. @Abhishek-kumar09 has suggested for a way to add a watch functionality to either 
- see the `upgrade status` as the job runs to successful completion or failure 
- or to tail the logs while running an upgrade

Both of the above are great ideas to simplify the UX for launching upgrade jobs for data plane, this issue will house the discussion for the same.

Continued from the discussions at #115

**Comment by Abhishek-kumar09** [comment]
Working on it.
