### ISSUE TITLE
Upgrade GitHub actions CI to use latest Golang binaries

### ISSUE THREAD

**Issue by vharsh** [openebs/openebsctl#146]
Currently the CI is using `Go 1.16`, it'll be great to move to `Go 1.17.7` for [smaller binary sizes, faster runtimes, ](https://go.dev/blog/go1.17).

# Steps

1. Become familiar with GitHub Actions
2. See how this project uses Golang GitHub actions
3. Bump up the `1.16` to `1.17.7`
4. Evaluate if anything else needs to be bumped up & if there's a GitHub action for the same & let us know about it in comments.

**Comment by MukulKolpe** [comment]
Hi @vharsh, Can I work on this issue?

**Comment by vharsh** [comment]
@MukulKolpe sure

**Comment by vharsh** [comment]
@MukulKolpe Make sure to sign your commits, i.e. when you create a commit with `git commit` just add a `-s` flag as suggested in the `CONTRIBUTING.md` of this repo.
