### ISSUE TITLE
Fix gocritic & golint(revive) issues in the codebase

### ISSUE THREAD

**Issue by vharsh** [openebs/openebsctl#147]
This issue is strictly for someone who has recently up Golang & would like to fix some code formatting issues.

I've recently fixed a small issue with GolangCI-lint(#105) in #145 & now the project has many warnings/suggestions & now they need fixing, currently those linters are disabled but do enable them after fixing all the issues.

# Steps

1. Learn a bit about GolangCI-Lint from it's official docs & a few blogs
2. Uncomment the enabled linters in GolangCI-Lint
3. Fix the code comment errors manually or figure out if the revive tool can autofix things for you(recommended).
4. Raise a PR & make sure to sign all your commits

**Comment by slothtae** [comment]
hello, I'm a contributor in operforce'22 I'm interested in golang can you assign me this issue.

**Comment by Abhinandan-Purkait** [comment]
GolangCI-Lint is already implemented. This can be closed now.
