### ISSUE TITLE
Determine openebs ns from the CLI.

### ISSUE THREAD

**Issue by Abhinandan-Purkait** [openebs/openebsctl#18]
We might need to rethink out K8sClient structure, as of now there are two candidates for similar resource fields

- namespace i.e. resource namespace for user created resources like pvc, pod, etc
- openebs-namespace i.e. the namespace where a specific Storage engine is installed

The `-n` flag is used to take the `pvc namespace` and same cannot be used to take the `openebs namespace` simultaneously.
Determining the `openebs` ns from the cli would help here.

**Comment by kmova** [comment]
- Check with ClusterRoleBinding or ServiceAccountName ( existence of `openebs.io` in labels) 
- Consider the possibility of jiva and openebs in different namespaces

**Comment by Abhinandan-Purkait** [comment]
We are tracking our approach and questionnaires in the respective document.
https://docs.google.com/document/d/1Zi8rPPWsxzpfTZrCScwoT4sAV_QSySMh2tjrpeKMqkE/edit
