### ISSUE TITLE
convert object blocks into object list

### ISSUE THREAD

**Issue by kmova** [openebs/openebsctl#24]
- `PrintByTemplate` may not be a good UI/UX as in case of multiple BDs the above will generate something like this:-
```
Block Device Details :
----------------
Name     : blockdevice-c21bc3b79a98c7e8508f47558cc94f36
Capacity : 107374182400
State   : Active
Block Device Details :
----------------
Name     : blockdevice-c21bc3b79a98c7e8508f47558cc94f36
Capacity : 107374182400
State   : Active
```
The above should have been like this, similar to `kubectl get` list.
```
Block Device Details :
----------------
Name   Capacity  State
bd-1   107641    active 
bd-2   187261    active
```
You can refer this code for the same:-
https://github.com/openebs/openebsctl/blob/de75453658baa6be23d739f3198df012e7c35f32/kubectl-openebs/cli/command/describe/pvc_info.go#L213

_Originally posted by @Abhinandan-Purkait in https://github.com/openebs/openebsctl/pull/20#discussion_r642222214_

**Comment by Abhinandan-Purkait** [comment]
@ParthS007 The above has been added as a part of cli-runtime refactor. Since it was a similar task it was included in the refactor. Thanks you.
