### ISSUE TITLE
Add go linting tools to CI

### ISSUE THREAD

**Issue by vharsh** [openebs/openebsctl#51]
# Background

[GolangCI-lint](https://golangci-lint.run/) is a popular linter for go-projects which has support for a lot of popular linters like govet, golint, gofmt, etc, so it gets a bit easier than having to write individual shell scripts & complex Makefiles. It's super configurable so it's warnings can be silenced & it runs with similar toggles locally, i.e. the config file works well for the local development & CI.

It has a host of tools like golint, gofmt, govet and a bunch of unofficial tools like dupl, depguard, etc which should be added. Per the docs, using the [official golangci-lint action](https://github.com/marketplace/actions/run-golangci-lint) might turn out to be a better approach than adding it via the Makefile in some other action/job.

**Comment by burntcarrot** [comment]
@vharsh I'd like to work on this, could you assign me?

**Comment by burntcarrot** [comment]
I'm not sure where the `Verify License` task should go.
https://github.com/openebs/openebsctl/blob/9001fb02a2d73b5f250951df10176220bfdb8602/.github/workflows/go.yml#L5-L23

And should this section be completely removed from the Makefile?
https://github.com/openebs/openebsctl/blob/9001fb02a2d73b5f250951df10176220bfdb8602/Makefile#L66-L73

Can you please clarify this?

**Comment by vharsh** [comment]
@burntcarrot You can move the license checking part to [goheader](https://golangci-lint.run/usage/configuration/) via GolangCI-lint & remove it from the go workflow.

Regarding the `golint:` target in Makefile, you can replace it with the `golangci-lint run` command & rename `golint` to `golangci` in Makefile
