### ISSUE TITLE
usability: message for no resources found

### ISSUE THREAD

**Issue by kmova** [openebs/openebsctl#56]
When the cluster doesn't have required resources, display a helpful message instead of displaying nothing. 

In my cluster that doesn't have any pools setup at, I get the following:
```
kiran_mova_mayadata_io@kmova-dev:~$ kubectl openebs get storage
kiran_mova_mayadata_io@kmova-dev:~$ 
```

It would nice to display a message like this:
```
kiran_mova_mayadata_io@kmova-dev:~$ kubectl get cspc
No resources found in default namespace.
```

Also, while at this - check the message displayed when there is no openebs installed in the cluster.

**Comment by vharsh** [comment]
Okay starting notes on implementation:

- For the volume & storage sub-commands, the code can run a single function(when cas-type is given in via flags) or run all functions when no `cas-type` flags are given.
- The code under interest is, `pkg/storage/storage.go`, `pkg/volume/volume.go`, `pkg/persistentvolumeclaim/persistentvolumeclaim.go` & `pkg/blockdevice/blockdevice.go`
- If a single function is executed(i.e. cas-type is supplied), a standard message & a standard error can be thrown by that cas-implementer function
- When cas-type isn't supplied, the errors might be stored in a slice & shown accordingly(a `volume` is a PersistentVolume, but a `storage` can be a two or three different kinds of resources, so having all errors would help)

For more help, do join the [OpenEBS-Dev slack](https://kubernetes.slack.com/archives/C015124PVTL/).

**Comment by Abhishek-kumar09** [comment]
Working on it.
