### ISSUE TITLE
Enhance `openebs version` command with installed component versions

### ISSUE THREAD

**Issue by kmova** [openebs/openebsctl#83]
The command `version` is only displaying the cli version. 
```
kubectl openebs version

Client Version: v0.2.0
```

It would be nice to enhance this with a few additional details (if openebs namespace can be determined) or manually specified like:

```
kubectl openebs version --openebs-namespace openebs

Client Version: v0.2.0
OpenEBS Version: 2.11.0
OpenEBS cStor: 2.11.1
OpenEBS Jiva: 2.11.0
OpenEBS ZFS Local PV: <Not installed>
....
```

(Almost like microk8s plugin status command)

Related: https://github.com/openebs/openebsctl/issues/36

**Comment by kmova** [comment]
Another cool addition would be to check if there is a newer CLI version that needs to be updated.

**Comment by vharsh** [comment]
> Another cool addition would be to check if there is a newer CLI version that needs to be updated.

This might be a bit easier as krew index will have the [latest version tag](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/openebs.yaml#L6)

**Comment by Abhishek-kumar09** [comment]
Would love to start with this beginner-friendly issue. Can I get assigned?

**Comment by Abhishek-kumar09** [comment]
@vharsh Should the versions be coming from kubernetes API, since the  openEBS will be running on kubernetes and the actual used versions can be found from this?
or it should be coming from the config or some manifest files?

Actually I am new to golang cli development and figuring out the the best possible way to do this.

**Comment by vharsh** [comment]
The OpenEBS component versions are set in the labels, to get the version of (say) Cstor storage engine, one can see the value of label key `openebs.io/version` on the Cstor CSI Statefulset.
